# Site settings
title: Haobo LI
description: > # this means to ignore newlines until "baseurl:"
   I'm currently a Ph.D. student at CSE department of HKUST, advised by Prof. Huamin Qu.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lihaobo.github.io" # the base hostname & protocol for your site
production_url: "https://lihaobo.github.io"
permalink: /blog/:year/:month/:title.html

# find me
email: hliem@connect.ust.hk
github_username: hobolee
github_url: https://github.com/hobolee
google_scholar_url:



sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
